Add fixed and dynamic frame broadcaster nodes
ros/geometry_tutorials pull request #40
Opened 2021-07-13 17:55 UTC by kurshakuz

Add fixed and dynamic frame broadcaster nodes that will be used in the upcoming Adding a Frame (Python) tutorial.

Signed-off-by: Shyngyskhan Abilkassov abilkasov@gmail.com

2021-07-14 11:02 UTC, ahcorde requested changes
we can include two new launch file to run each one of the examples.
 - one launch file for the dynamic_frame 
 - one launch file for the fixed_frame

2021-07-14 11:15 UTC, ahcorde requested changes
What do you think about modify `turtle_tf2_listener` to allow introducing the target as a ros argument ?

2021-07-14 15:52 UTC, kurshakuz commented
> we can include two new launch file to run each one of the examples.
> 
> * one launch file for the dynamic_frame
> * one launch file for the fixed_frame

Do you think that this code files would not be redundant? Both of them will be based on the `turtle_tf2_demo.launch.py` and all three will be very alike. The only difference would be the added last node.

However, it would be perfect if we can do nested launch files. I know there was a way to include launch files into each other in the first ROS, but I have not seen examples of doing so in the ROS 2 launch files. 




> What do you think about modify `turtle_tf2_listener` to allow introducing the target as a ros argument ?

I think it would be great! I also think it would be better for users to update the arguments rather than the code itself. I will do that now. Thanks for the idea

2021-07-14 15:58 UTC, ahcorde commented
> Do you think that this code files would not be redundant? Both of them will be based on the turtle_tf2_demo.launch.py and all three will be very alike. The only difference would be the added last node.

>However, it would be perfect if we can do nested launch files. I know there was a way to include launch files into each other in the first ROS, but I have not seen examples of doing so in the ROS 2 launch files.

You can include another launch file with something like this

```python
    gazebo = IncludeLaunchDescription(
                PythonLaunchDescriptionSource([os.path.join(
                    get_package_share_directory('gazebo_ros'), 'launch'), '/gazebo.launch.py']),
             )
   ...

    return LaunchDescription([
        gazebo, 
        Node(....)
    ])
```

2021-07-16 09:01 UTC, ahcorde requested changes

2021-07-16 09:01 UTC, ahcorde commented on turtle_tf2_py/launch/turtle_tf2_dynamic_frame_demo.launch.py
> +            '/turtle_tf2_demo.launch.py']),
Merge with master and include `launch_arguments`

```python
            launch_arguments={'target_frame': 'carrot1'}.items(),
```

2021-07-19 16:49 UTC, ahcorde requested changes

2021-07-19 16:49 UTC, ahcorde commented on turtle_tf2_py/launch/turtle_tf2_fixed_frame_demo.launch.py
> +
```suggestion
```

2021-07-19 16:49 UTC, ahcorde commented on turtle_tf2_py/launch/turtle_tf2_dynamic_frame_demo.launch.py
> +
```suggestion
```

2021-07-20 10:54 UTC, ahcorde approved these changes

2021-07-20 10:54 UTC, merged