Add target frame parameter to the listener node
ros/geometry_tutorials pull request #41
Opened 2021-07-14 18:04 UTC by kurshakuz

Add target frame parameter to the listener node

Signed-off-by: Shyngyskhan Abilkassov abilkasov@gmail.com

2021-07-14 18:34 UTC, ahcorde requested changes
I would like to modify the value using the command line, here you have an [example](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/foxy/gazebo_ros/launch/gzclient.launch.py). Take a look to `extra_gazebo_args`

2021-07-16 08:58 UTC, ahcorde approved these changes

2021-07-16 08:58 UTC, merged

2021-07-16 08:58 UTC, ahcorde commented
Do you mind to update the docs (if necessary) ?

2021-07-16 16:56 UTC, kurshakuz commented
> Do you mind to update the docs (if necessary) ?

Yes, I will update my WIP documentation PR to include those updates