Remove the dependency on tf_transformations.
ros/geometry_tutorials pull request #69
Opened 2022-08-12 20:35 UTC by clalancette

That way we don't have to install a non-standard library
(tf_transformations) that depends on a non-packaged pip
package (transforms3d) for the tutorials to work.

Note well that the function is copied twice, once in
static_turtle_tf2_broadcaster.py and once in turtle_tf2_broadcaster.py.
This is by design, as these files are used as standalone
examples in the ROS 2 tutorials.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

2022-08-17 21:34 UTC, audrow approved these changes
Looks good to me!

2022-08-18 09:39 UTC, ahcorde approved these changes

2022-08-18 09:43 UTC, ahcorde requested changes
There are some linters issues in rolling?

should we need to add github actions for humble too? In a new PR? I can take care

2022-08-19 14:34 UTC, clalancette commented
Rebased onto the latest; this should hopefully fix CI.

2022-08-22 07:15 UTC, ahcorde approved these changes

2022-08-22 07:16 UTC, merged