Migrate std::bind calls to lambda expressions
ros/geometry_tutorials pull request #76
Opened 2024-01-08 13:31 UTC by FelipeGdM

This PR is a follow up to the changes made in the documentation https://github.com/ros2/ros2_documentation/pull/4041

The migration of std::bind calls made in the docs is reflected here

2024-01-08 14:00 UTC, ahcorde approved these changes

2024-01-08 14:05 UTC, clalancette requested changes
Two changes to pass linters, then this is probably good to go.

2024-01-08 14:05 UTC, clalancette commented on turtle_tf2_cpp/src/turtle_tf2_broadcaster.cpp
> +    auto handle_turtle_pose = [this](const std::shared_ptr<turtlesim::msg::Pose> msg){
```suggestion
    auto handle_turtle_pose = [this](const std::shared_ptr<turtlesim::msg::Pose> msg) {
```

2024-01-08 14:05 UTC, clalancette commented on turtle_tf2_cpp/src/turtle_tf2_broadcaster.cpp
> +    };
```suggestion
      };
```

2024-01-08 14:45 UTC, clalancette requested changes
One more linter error (not sure why this didn't show up in the earlier run).

2024-01-08 14:45 UTC, clalancette commented on turtle_tf2_cpp/src/turtle_tf2_listener.cpp
> +      1s, [this](){return this->on_timer();});
```suggestion
      1s, [this]() {return this->on_timer();});
```

2024-01-09 14:09 UTC, ahcorde requested changes
```bash
2024-01-08T15:02:27.9197222Z 7: --- src/turtle_tf2_listener.cpp
2024-01-08T15:02:27.9197566Z 7: +++ src/turtle_tf2_listener.cpp.uncrustify
2024-01-08T15:02:27.9197935Z 7: @@ -56 +56 @@
2024-01-08T15:02:27.9198266Z 7: -      1s, [this](){return this->on_timer();});
2024-01-08T15:02:27.9198687Z 7: +      1s, [this]() {return this->on_timer();});
```

2024-01-10 12:31 UTC, FelipeGdM commented
I executed `ament_uncrustify src/` locally to be sure all format errors are solved >.<

2024-01-10 14:08 UTC, merged