Clean rolling CI
ros/geometry_tutorials pull request #82
Opened 2024-06-28 11:21 UTC by ahcorde

2024-06-28 16:56 UTC, clalancette commented
The change looks OK to me, but this is failing because I think https://github.com/ros/geometry_tutorials/blob/6481e8fa9b5cef611f3d6d3aea2ea338701c481a/turtle_tf2_cpp/src/turtle_tf2_message_filter.cpp#L55 needs to be updated to pass in a QoS parameter.

2024-07-11 10:25 UTC, ahcorde commented
@clalancette friendly ping

2024-07-11 12:24 UTC, clalancette requested changes

2024-07-11 12:24 UTC, clalancette commented on turtle_tf2_cpp/src/turtle_tf2_message_filter.cpp
> +      rclcpp::QoS(rclcpp::QoSInitialization::from_rmw(rmw_qos_profile_default)));
Especially given that this is one of our examples, I think this is a little wordy.  We can simplify this to:

```suggestion
    point_sub_.subscribe(this, "/turtle3/turtle_point_stamped", rclcpp::QoS(10));
```

(this probably points out a deficiency in our QoS APIs for this, but at least the above doesn't look as scary)

2024-07-11 13:20 UTC, clalancette approved these changes
Looks good to me with green CI.

2024-07-11 16:06 UTC, merged